"""empty message

Revision ID: 5ae56dc30b3a
Revises: d3e698ebf3f2
Create Date: 2023-04-07 10:22:48.196570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae56dc30b3a'
down_revision = 'd3e698ebf3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('crop', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('variety', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('season', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('soil_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('crop_duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('irrigation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('irrigation')
        batch_op.drop_column('crop_duration')
        batch_op.drop_column('soil_type')
        batch_op.drop_column('season')
        batch_op.drop_column('variety')
        batch_op.drop_column('crop')
        batch_op.drop_column('crop_group')

    # ### end Alembic commands ###
