"""empty message

Revision ID: e6ce7b36ff0a
Revises: 
Create Date: 2023-04-04 20:15:14.192042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ce7b36ff0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('prev_crop', sa.String(length=100), nullable=False),
    sa.Column('crop_group', sa.String(length=100), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('crop_duration', sa.String(length=100), nullable=True),
    sa.Column('irrigation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
